"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Tags = exports.foods = void 0;
exports.foods = [
    {
        id: '1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        realPrice: 100,
        favorite: false,
        origins: ['italy'],
        des: "Ngon tuyeệt cú mèo",
        stars: 4.5,
        imageUrl: 'assets/img/food-1.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Meatball',
        price: 20,
        realPrice: 100,
        cookTime: '20-30',
        des: "Ngon tuyeệt cú mèo",
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'assets/img/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'Hamburger',
        price: 5,
        realPrice: 100,
        cookTime: '10-15',
        des: "Ngon tuyeệt cú mèo",
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'assets/img/food-3.jpg',
        tags: ['Fastfood', 'Hamburger'],
    },
    {
        id: '4',
        name: 'Fried Potatoes',
        price: 2,
        realPrice: 100,
        des: "Ngon tuyeệt cú mèo",
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'assets/img/food-4.jpg',
        tags: ['Fastfood', 'Fry'],
    },
    {
        id: '5',
        name: 'Chicken Soup',
        price: 11,
        realPrice: 100,
        cookTime: '40-50',
        des: "Ngon tuyeệt cú mèo",
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'assets/img/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        price: 9,
        realPrice: 100,
        cookTime: '40-50',
        favorite: false,
        des: "Ngon tuyeệt cú mèo",
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/img/food-6.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        price: 9,
        realPrice: 100,
        cookTime: '40-50',
        favorite: false,
        des: "Ngon tuyeệt cú mèo",
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/img/food-6.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        price: 9,
        realPrice: 100,
        cookTime: '40-50',
        favorite: false,
        des: "Ngon tuyeệt cú mèo",
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/img/food-6.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        price: 9,
        realPrice: 100,
        des: "Ngon tuyeệt cú mèo",
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/img/food-6.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        price: 9,
        des: "Ngon tuyeệt cú mèo",
        realPrice: 100,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/img/food-6.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
];
exports.Tags = [
    { name: 'All', count: 6 },
    { name: 'Fastfood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
];
